CREATE TABLE `metaCampaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` varchar(255) NOT NULL,
	`campaignName` varchar(255) NOT NULL,
	`objective` varchar(100),
	`status` varchar(50),
	`impressions` int NOT NULL DEFAULT 0,
	`clicks` int NOT NULL DEFAULT 0,
	`linkClicks` int NOT NULL DEFAULT 0,
	`spend` decimal(12,2) NOT NULL DEFAULT '0',
	`reach` int NOT NULL DEFAULT 0,
	`results` int NOT NULL DEFAULT 0,
	`costPerResult` decimal(12,2),
	`videoThreeSecondPlays` int DEFAULT 0,
	`videoPlays` int DEFAULT 0,
	`ctr` decimal(8,4) DEFAULT '0',
	`cpm` decimal(12,2) DEFAULT '0',
	`cpc` decimal(12,2) DEFAULT '0',
	`roas` decimal(8,2),
	`startDate` timestamp,
	`endDate` timestamp,
	`dataFetchedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `metaCampaigns_id` PRIMARY KEY(`id`),
	CONSTRAINT `metaCampaigns_campaignId_unique` UNIQUE(`campaignId`)
);
